INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AAL', 'Aalborg', 'Aalborg', 'Aalborg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AAR', 'Aarhus', 'Aarhus', 'Aarhus');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ABZ', 'Aberdeen', 'Aberdeen', 'Aberdeen');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ACE', 'Lanzarote', 'Lanzarote', 'Lanzarote');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AGA', 'Agadir', 'Agadir', 'Agadir');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AGP', 'Malaga', 'Malaga', 'Malaga');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AHO', 'Alghero', 'Alghero', 'Alghero');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ALC', 'Alicante', 'Alicante', 'Alicante');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AMM', 'Amman Jordan', 'Amman', 'Amman');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AMS', 'Amsterdam', 'Amsterdam', 'Amsterdam');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AOI', 'Ancona', 'Ancona', 'Ancona');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AQJ', 'Aqaba Jordan', 'Aqaba', 'Aqaba');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ATH', 'Athens', 'Athens', 'Athens');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('AYT', 'Antalya', 'Antalya', 'Antalya');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BCN', 'Barcelona', 'Barcelona', 'Barcelona');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BDS', 'Brindisi', 'Brindisi', 'Brindisi');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BES', 'Brest', 'Brest', 'Brest');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BEY', 'Beirut', 'Beirut', 'Beirut');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BFS', 'Belfast International', 'Belfast', 'Belfast');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BGY', 'Milan Bergamo', 'Milan', 'Milan');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BHX', 'Birmingham', 'Birmingham', 'Birmingham');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BIO', 'Bilbao', 'Bilbao', 'Bilbao');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BIQ', 'Biarritz', 'Biarritz', 'Biarritz');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BJV', 'Bodrum', 'Bodrum', 'Bodrum');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BLL', 'Billund', 'Billund', 'Billund');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BLQ', 'Bologna', 'Bologna', 'Bologna');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BNX', 'Banja Luka', 'Banja Luka', 'Banja Luka');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BOD', 'Bordeaux', 'Bordeaux', 'Bordeaux');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BOH', 'Bournemouth', 'Bournemouth', 'Bournemouth');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BOJ', 'Burgas', 'Burgas', 'Burgas');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BRE', 'Bremen', 'Bremen', 'Bremen');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BRI', 'Bari', 'Bari', 'Bari');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BRQ', 'Brno', 'Brno', 'Brno');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BRS', 'Bristol', 'Bristol', 'Bristol');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BRU', 'Brussels', 'Brussels', 'Brussels');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BSL', 'Basel', 'Basel', 'Basel');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BTS', 'Bratislava', 'Bratislava', 'Bratislava');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BUD', 'Budapest', 'Budapest', 'Budapest');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BVA', 'Paris Beauvais', 'Paris', 'Paris');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BVE', 'Brive', 'Brive', 'Brive');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BZG', 'Bydgoszcz', 'Bydgoszcz', 'Bydgoszcz');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('BZR', 'Beziers', 'Beziers', 'Beziers');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CAG', 'Cagliari', 'Cagliari', 'Cagliari');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CCF', 'Carcassonne', 'Carcassonne', 'Carcassonne');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CDT', 'Castellon (Valencia)', 'Castellon', 'Castellon');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CFE', 'Clermont', 'Clermont Ferrand', 'Clermont Ferrand');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CFU', 'Corfu', 'Corfu', 'Corfu');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CGN', 'Cologne', 'Cologne', 'Cologne');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CHQ', 'Chania', 'Chania', 'Chania');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CIA', 'Rome Ciampino', 'Rome', 'Rome');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CIY', 'Comiso', 'Comiso', 'Comiso');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CLJ', 'Cluj', 'Cluj', 'Cluj');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CMN', 'Casablanca', 'Casablanca', 'Casablanca');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CPH', 'Copenhagen', 'Copenhagen', 'Copenhagen');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CRL', 'Brussels Charleroi', 'Charleroi', 'Charleroi');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CRV', 'Crotone', 'Crotone', 'Crotone');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CTA', 'Catania', 'Catania', 'Catania');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CUF', 'Cuneo', 'Cuneo', 'Cuneo');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('CWL', 'Cardiff', 'Cardiff', 'Cardiff');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DBV', 'Dubrovnik', 'Dubrovnik', 'Dubrovnik');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DLE', 'Dole', 'Dole', 'Dole');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DLM', 'Dalaman', 'Dalaman', 'Dalaman');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DNR', 'Dinard', 'Dinard', 'Dinard');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DRS', 'Dresden', 'Dresden', 'Dresden');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DTM', 'Dortmund', 'Dortmund', 'Dortmund');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DUB', 'Dublin', 'Dublin', 'Dublin');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('DUS', 'Dusseldorf Int.', 'Dusseldorf', 'Dusseldorf');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('EDI', 'Edinburgh', 'Edinburgh', 'Edinburgh');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('EFL', 'Kefalonia', 'Kefalonia', 'Kefalonia');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('EGC', 'Bergerac', 'Bergerac', 'Bergerac');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('EIN', 'Eindhoven', 'Eindhoven', 'Eindhoven');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('EMA', 'East Midlands', 'East Midlands', 'East Midlands');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ERF', 'Erfurt', 'Erfurt', 'Erfurt');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ESU', 'Essaouira', 'Essaouira', 'Essaouira');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ETM', 'Eilat Ramon', 'Eilat', 'Eilat');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('EVN', 'Yerevan - Zvartnots', 'Yerevan', 'Yerevan');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('EXT', 'Exeter', 'Exeter', 'Exeter');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FAO', 'Faro', 'Faro', 'Faro');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FCO', 'Rome Fiumicino', 'Rome', 'Rome');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FDH', 'Friedrichshafen', 'Friedrichshafen', 'Friedrichshafen');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FEZ', 'Fez', 'Fez', 'Fez');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FKB', 'Karlsruhe / Baden-Baden', 'Karlsruhe', 'Karlsruhe');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FMM', 'Memmingen', 'Memmingen', 'Memmingen');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FMO', 'Münster', 'Münster', 'Münster');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FNI', 'Nimes', 'Nimes', 'Nimes');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FRA', 'Frankfurt International', 'Frankfurt', 'Frankfurt');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FSC', 'Figari', 'Figari', 'Figari');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('FUE', 'Fuerteventura', 'Fuerteventura', 'Fuerteventura');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('GDN', 'Gdansk', 'Gdansk', 'Gdansk');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('GLA', 'Glasgow', 'Glasgow', 'Glasgow');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('GNB', 'Grenoble', 'Grenoble', 'Grenoble');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('GOA', 'Genoa', 'Genoa', 'Genoa');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('GOT', 'Göteborg Landvetter', 'Gothenburg', 'Gothenburg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('GRO', 'Barcelona Girona', 'Girona', 'Girona');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('GVA', 'Geneva', 'Geneva', 'Geneva');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('HAJ', 'Hannover', 'Hannover', 'Hannover');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('HAM', 'Hamburg', 'Hamburg', 'Hamburg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('HAU', 'Haugesund', 'Haugesund', 'Haugesund');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('HEL', 'Helsinki', 'Helsinki', 'Helsinki');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('HER', 'Heraklion Crete', 'Heraklion', 'Heraklion');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('HHN', 'Frankfurt Hahn', 'Frankfurt', 'Frankfurt');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('HRK', 'Kharkiv International', 'Kharkiv', 'Kharkiv');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('IBZ', 'Ibiza', 'Ibiza', 'Ibiza');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('INI', 'Nis', 'Nis', 'Nis');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('JMK', 'Mykonos', 'Mykonos', 'Mykonos');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('JSI', 'Skiathos', 'Skiathos', 'Skiathos');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('JTR', 'Santorini', 'Santorini', 'Santorini');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KBP', 'Kyiv', 'Kyiv', 'Kyiv');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KGS', 'Kos', 'Kos', 'Kos');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KHE', 'Kherson', 'Kherson', 'Kherson');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KIR', 'Kerry', 'Kerry', 'Kerry');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KLU', 'Klagenfurt', 'Klagenfurt', 'Klagenfurt');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KLX', 'Kalamata', 'Kalamata', 'Kalamata');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KRK', 'Krakow', 'Krakow', 'Krakow');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KSC', 'Kosice', 'Kosice', 'Kosice');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KTW', 'Katowice', 'Katowice', 'Katowice');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KUN', 'Kaunas', 'Kaunas', 'Kaunas');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KUT', 'Kutaisi', 'Kutaisi', 'Kutaisi');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('KVA', 'Kavala International', 'Kavala', 'Kavala');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LBA', 'Leeds Bradford', 'Leeds', 'Leeds');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LCA', 'Larnaca', 'Larnaca', 'Larnaca');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LCJ', 'Lodz', 'Lodz', 'Lodz');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LDE', 'Lourdes', 'Lourdes', 'Lourdes');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LDY', 'Derry', 'Derry', 'Derry');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LED', 'St. Petersburg', 'Saint Petersburg', 'Saint Petersburg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LEI', 'Almeria', 'Almeria', 'Almeria');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LGW', 'London Gatwick', 'London', 'London');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LIG', 'Limoges', 'Limoges', 'Limoges');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LIL', 'Lille', 'Lille', 'Lille');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LIS', 'Lisbon', 'Lisbon', 'Lisbon');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LPA', 'Gran Canaria', 'Gran Canaria', 'Gran Canaria');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LPL', 'Liverpool', 'Liverpool', 'Liverpool');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LPP', 'Lappeenranta', 'Lappeenranta', 'Lappeenranta');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LRH', 'La Rochelle', 'La Rochelle', 'La Rochelle');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LTN', 'London Luton', 'London', 'London');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LUX', 'Luxembourg', 'Luxembourg', 'Luxembourg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LUZ', 'Lublin', 'Lublin', 'Lublin');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LWN', 'Gyumri – Shirak', 'Gyumri', 'Gyumri');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LWO', 'Lviv', 'Lviv', 'Lviv');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('LYS', 'Lyon', 'Lyon', 'Lyon');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MAD', 'Madrid', 'Madrid', 'Madrid');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MAH', 'Menorca', 'Menorca', 'Menorca');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MAN', 'Manchester', 'Manchester', 'Manchester');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MJV', 'Murcia', 'Murcia', 'Murcia');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MLA', 'Malta', 'Malta', 'Malta');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MMX', 'Malmo', 'Malmo', 'Malmo');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MRS', 'Marseille', 'Marseille', 'Marseille');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MST', 'Maastricht', 'Maastricht', 'Maastricht');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MUC', 'Munich', 'Munich', 'Munich');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('MXP', 'Milan Malpensa', 'Milan', 'Milan');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NAP', 'Naples', 'Naples', 'Naples');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NCE', 'Nice', 'Nice', 'Nice');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NCL', 'Newcastle', 'Newcastle', 'Newcastle');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NDR', 'Nador', 'Nador', 'Nador');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NOC', 'Knock', 'Knock', 'Knock');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NQY', 'Newquay Cornwall', 'Newquay', 'Newquay');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NRN', 'Dusseldorf Weeze', 'Dusseldorf', 'Dusseldorf');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NTE', 'Nantes', 'Nantes', 'Nantes');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NUE', 'Nuremberg', 'Nuremberg', 'Nuremberg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('NYO', 'Stockholm Skavsta', 'Stockholm', 'Stockholm');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ODS', 'Odesa International', 'Odessa', 'Odessa');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('OMR', 'Oradea', 'Oradea', 'Oradea');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('OPO', 'Porto', 'Porto', 'Porto');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ORK', 'Cork', 'Cork', 'Cork');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('OSL', 'Oslo', 'Oslo', 'Oslo');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('OSR', 'Ostrava', 'Ostrava', 'Ostrava');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('OTP', 'Bucharest', 'Bucharest', 'Bucharest');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('OUD', 'Oujda', 'Oujda', 'Oujda');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('OZZ', 'Ouarzazate', 'Ouarzazate', 'Ouarzazate');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PDL', 'Ponta Delgada', 'Ponta Delgada', 'Ponta Delgada');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PDV', 'Plovdiv', 'Plovdiv', 'Plovdiv');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PED', 'Pardubice', 'Pardubice', 'Pardubice');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PEG', 'Perugia', 'Perugia', 'Perugia');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PFO', 'Paphos', 'Paphos', 'Paphos');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PGF', 'Perpignan', 'Perpignan', 'Perpignan');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PIK', 'Glasgow Prestwick', 'Glasgow', 'Glasgow');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PIS', 'Poitiers', 'Poitiers', 'Poitiers');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PLQ', 'Palanga', 'Palanga', 'Palanga');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PMF', 'Parma', 'Parma', 'Parma');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PMI', 'Palma de Mallorca', 'Palma', 'Palma');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PMO', 'Palermo', 'Palermo', 'Palermo');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('POZ', 'Poznan', 'Poznan', 'Poznan');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PRG', 'Prague', 'Prague', 'Prague');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PSA', 'Pisa', 'Pisa', 'Pisa');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PSR', 'Pescara', 'Pescara', 'Pescara');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PUY', 'Pula', 'Pula', 'Pula');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('PVK', 'Preveza - Aktion', 'Preveza', 'Preveza');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RAK', 'Marrakesh', 'Marrakesh', 'Marrakesh');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RBA', 'Rabat', 'Rabat', 'Rabat');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RDZ', 'Rodez', 'Rodez', 'Rodez');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('REU', 'Barcelona Reus', 'Reus', 'Reus');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RHO', 'Rhodes', 'Rhodes', 'Rhodes');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RIX', 'Riga', 'Riga', 'Riga');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RJK', 'Rijeka', 'Rijeka', 'Rijeka');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RLG', 'Rostock', 'Rostock', 'Rostock');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RMI', 'Rimini', 'Rimini', 'Rimini');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RMU', 'Murcia International', 'Murcia', 'Murcia');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('RZE', 'Rzeszow', 'Rzeszow', 'Rzeszow');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SCQ', 'Santiago', 'Santiago', 'Santiago');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SDR', 'Santander', 'Santander', 'Santander');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SEN', 'London Southend', 'Southend-on-Sea', 'Southend-on-Sea');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SKG', 'Thessaloniki', 'Thessaloniki', 'Thessaloniki');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SNN', 'Shannon', 'Shannon', 'Shannon');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SOF', 'Sofia', 'Sofia', 'Sofia');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SPU', 'Split', 'Split', 'Split');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('STN', 'London Stansted', 'London', 'London');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('STR', 'Stuttgart', 'Stuttgart', 'Stuttgart');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SUF', 'Lamezia', 'Lamezia', 'Lamezia');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SVO', 'Moscow Sheremetyevo', 'Moscow', 'Moscow');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SVQ', 'Seville', 'Seville', 'Seville');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SXB', 'Strasbourg', 'Strasbourg', 'Strasbourg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SXF', 'Berlin Schönefeld', 'Berlin', 'Berlin');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SZG', 'Salzburg', 'Salzburg', 'Salzburg');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SZY', 'Olsztyn - Mazury', 'Olsztyn', 'Olsztyn');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('SZZ', 'Szczecin', 'Szczecin', 'Szczecin');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TBS', 'Tbilisi', 'Tbilisi', 'Tbilisi');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TER', 'Terceira Lajes', 'Terceira', 'Terceira');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TFN', 'Tenerife North', 'Tenerife', 'Tenerife');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TFS', 'Tenerife South', 'Tenerife', 'Tenerife');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TGD', 'Podgorica', 'Podgorica', 'Podgorica');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TLL', 'Tallinn', 'Tallinn', 'Tallinn');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TLS', 'Toulouse', 'Toulouse', 'Toulouse');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TLV', 'Tel Aviv', 'Tel Aviv', 'Tel Aviv');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TMP', 'Tampere', 'Tampere', 'Tampere');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TNG', 'Tangier', 'Tangier', 'Tangier');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TPS', 'Trapani', 'Trapani', 'Trapani');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TRF', 'Oslo Torp', 'Sandefjord', 'Sandefjord');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TRN', 'Turin', 'Turin', 'Turin');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TRS', 'Trieste', 'Trieste', 'Trieste');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TSF', 'Venice Treviso', 'Venice', 'Venice');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TSR', 'Timisoara', 'Timisoara', 'Timisoara');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TTU', 'Tétouan', 'Tétouan', 'Tétouan');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TUF', 'Tours Loire Valley', 'Tours', 'Tours');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TUN', 'Tunis', 'Tunis', 'Tunis');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('TXL', 'Berlin Tegel', 'Berlin', 'Berlin');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VAR', 'Varna', 'Varna', 'Varna');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VCE', 'Venice M.Polo', 'Venice', 'Venice');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VDA', 'Ovda', 'Eilat', 'Eilat');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VIE', 'Vienna', 'Vienna', 'Vienna');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VIT', 'Vitoria (Basque Country)', 'Vitoria-Gasteiz', 'Vitoria-Gasteiz');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VLC', 'Valencia', 'Valencia', 'Valencia');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VLL', 'Valladolid', 'Valladolid', 'Valladolid');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VNO', 'Vilnius', 'Vilnius', 'Vilnius');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VRN', 'Verona', 'Verona', 'Verona');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VST', 'Stockholm Västerås', 'Stockholm', 'Stockholm');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('VXO', 'Växjö Småland', 'Växjö', 'Växjö');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('WMI', 'Warsaw Modlin', 'Warsaw', 'Warsaw');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('WRO', 'Wroclaw', 'Wroclaw', 'Wroclaw');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('XCR', 'Paris Vatry', 'Paris', 'Paris');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('XRY', 'Jerez', 'Jerez', 'Jerez');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ZAD', 'Zadar', 'Zadar', 'Zadar');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ZAZ', 'Zaragoza', 'Zaragoza', 'Zaragoza');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ZRH', 'Zurich', 'Zurich', 'Zurich');
INSERT INTO airports(iata_code, airport_name, city_name, country_name) VALUES ('ZTH', 'Zakynthos', 'Zakynthos', 'Zakynthos');
